/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module priority_encoder_2to4(req, enc, valid);
  input [3:0] req;
  wire [3:0] req;
  output [1:0] enc;
  wire [1:0] enc;
  output valid;
  wire valid;
  wire [1:0] _0_;
  wire _1_;
  wire _2_;
  \$_MUX_  _3_ (
    .A(req[0]),
    .B(1'h1),
    .S(req[1]),
    .Y(_2_)
  );
  \$_MUX_  _4_ (
    .A(_2_),
    .B(1'h1),
    .S(req[2]),
    .Y(_1_)
  );
  \$_MUX_  _5_ (
    .A(req[1]),
    .B(1'h0),
    .S(req[2]),
    .Y(_0_[0])
  );
  \$_MUX_  _6_ (
    .A(_1_),
    .B(1'h1),
    .S(req[3]),
    .Y(valid)
  );
  \$_MUX_  _7_ (
    .A(_0_[0]),
    .B(1'h1),
    .S(req[3]),
    .Y(enc[0])
  );
  \$_MUX_  _8_ (
    .A(req[2]),
    .B(1'h1),
    .S(req[3]),
    .Y(enc[1])
  );
  assign _0_[1] = req[2];
endmodule
